### ISSUE TITLE
Learn-test command does not work

### ISSUE THREAD

**Issue by Laveeshka** [learn-co-curriculum/phase-1-html-forms-lab#2]
<img width="638" alt="Screen Shot 2022-10-10 at 11 33 40 pm" src="https://user-images.githubusercontent.com/111683695/194867240-785b29eb-0785-4aa7-b226-660b8424a5e0.png">

**Comment by lizbur10** [comment]
Hi @Laveeshka - so sorry you ran into problems with this!

Based on your description, it sounds like the issue may be related to your environment setup rather than with the lesson
itself or the instructions. The curriculum team monitors these issues so that we can fix typos and bugs in the curriculum, but we aren't equipped to provide support.

To get help with your question, you should either:

- Reach out to your instructor (if you've started the program and have an instructor)
- Use the [Pair with a TC (https://docs.google.com/document/d/1Gko5UFzCBhpo1R0V_Tx2JHSK9cRC2b_53Ky3u5Qtzlk/edit) feature in Canvas to connect with a Technical Coach on the Academic Success Team

Please re-open this issue if you believe the lesson needs to be updated.

Hope you were able to get this resolved!
